export const columns = [
  { name: 'ORDER ID', uid: 'orderId' },
  { name: 'CUSTOMER NAME', uid: 'customerName' },
  { name: 'EMAIL', uid: 'email' },
  { name: 'PRODUCT', uid: 'product' },
  { name: 'QTY', uid: 'quantity' },
  { name: 'TOTAL PRICE', uid: 'totalPrice' },
  { name: 'DATE', uid: 'orderDate' },
  { name: 'STATUS', uid: 'status' },
  { name: 'ACTIONS', uid: 'actions' },
];

export const data = [
    {
      id: 1,
      orderId: 'ORD001',
      customerName: 'John Doe',
      product: 'Laptop',
      quantity: 1,
      status: 'Pending',
      orderDate: '2024-12-01',
      totalPrice: 1200.00,
      email: 'john.doe@example.com',
    },
    {
      id: 2,
      orderId: 'ORD002',
      customerName: 'Jane Smith',
      product: 'Smartphone',
      quantity: 2,
      status: 'Shipped',
      orderDate: '2024-12-02',
      totalPrice: 1400.00,
      email: 'jane.smith@example.com',
    },
    {
      id: 3,
      orderId: 'ORD003',
      customerName: 'Alice Brown',
      product: 'Headphones',
      quantity: 3,
      status: 'Delivered',
      orderDate: '2024-11-28',
      totalPrice: 300.00,
      email: 'alice.brown@example.com',
    },
    {
      id: 4,
      orderId: 'ORD004',
      customerName: 'Bob Johnson',
      product: 'Tablet',
      quantity: 1,
      status: 'Cancelled',
      orderDate: '2024-11-30',
      totalPrice: 400.00,
      email: 'bob.johnson@example.com',
    },
    {
      id: 5,
      orderId: 'ORD005',
      customerName: 'Charlie Green',
      product: 'Smartwatch',
      quantity: 1,
      status: 'Pending',
      orderDate: '2024-12-03',
      totalPrice: 250.00,
      email: 'charlie.green@example.com',
    },
    {
      id: 6,
      orderId: 'ORD006',
      customerName: 'Eve White',
      product: 'Monitor',
      quantity: 2,
      status: 'Shipped',
      orderDate: '2024-12-02',
      totalPrice: 800.00,
      email: 'eve.white@example.com',
    },
];



